@sst ..\assets\cube.png ..\Bin\cube.sst RGBA
@sst ..\assets\titlehint.png ..\Bin\titlehint.sst RGBA
@sst ..\assets\cursor.png ..\Bin\cursor.sst RGBA
@sst ..\assets\1.png ..\Bin\num1.sst RGBA
@sst ..\assets\2.png ..\Bin\num2.sst RGBA
@sst ..\assets\3.png ..\Bin\num3.sst RGBA
@sst ..\assets\4.png ..\Bin\num4.sst RGBA
@sst ..\assets\5.png ..\Bin\num5.sst RGBA
@sst ..\assets\6.png ..\Bin\num6.sst RGBA
@sst ..\assets\locked.png ..\Bin\locked.sst RGBA
@sst ..\assets\back.png ..\Bin\back.sst RGBA
@sst ..\assets\nums.png ..\Bin\nums.sst RGBA
@sst ..\assets\help.png ..\Bin\help.sst RGBA
@sst ..\assets\finish.png ..\Bin\finish.sst RGBA
@sst ..\assets\list.png ..\Bin\list.sst RGBA
@sst ..\assets\restart.png ..\Bin\restart.sst RGBA
@sst ..\assets\next.png ..\Bin\next.sst RGBA