@sst ..\assets\cube.png ..\Bin\cube.sst RGBA
@sst ..\assets\titlehint.png ..\Bin\titlehint.sst RGBA
@sst ..\assets\cursor.png ..\Bin\cursor.sst RGBA
@sst ..\assets\1.png ..\Bin\num1.sst RGBA
@sst ..\assets\2.png ..\Bin\num2.sst RGBA
@sst ..\assets\3.png ..\Bin\num3.sst RGBA
@sst ..\assets\4.png ..\Bin\num4.sst RGBA
@sst ..\assets\5.png ..\Bin\num5.sst RGBA
@sst ..\assets\6.png ..\Bin\num6.sst RGBA
@sst ..\assets\locked.png ..\Bin\locked.sst RGBA
@sst ..\assets\back.png ..\Bin\back.sst RGBA
